# Generated by Django 4.1.1 on 2023-08-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('date', models.DateField()),
                ('num_adults', models.PositiveIntegerField()),
                ('num_children', models.PositiveIntegerField()),
                ('state', models.CharField(max_length=50)),
            ],
        ),
    ]
