# Generated by Django 4.2.5 on 2024-08-07 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_register'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='User',
        ),
    ]
