# Generated by Django 4.2.5 on 2024-08-10 11:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0005_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('category', models.TextField()),
                ('title', models.TextField()),
                ('bannerImage', models.ImageField(upload_to='blog_images/')),
                ('content', models.TextField()),
            ],
        ),
    ]
